# The configuration file for IMPSY: Interactive Musical Prediction System

# Metadata about this configuration
title = "Casio CDP-S150 Configuration"
owner = "Scott Howsam"
description = "Uses USB connection to a Casio CDP-S150 keyboard"

# Basic config
log = true
log_predictions = false
verbose = true

# Interaction Configuration
[interaction]
mode = "callresponse" # Can be: "callresponse", "polyphony", "battle", "useronly"
threshold = 1.1 # number of seconds before switching in call-response mode
input_thru = false # sends inputs directly to outputs (e.g., if input interface is different than output synth)

# Model configuration
[model]
dimension = 2
file = "models/musicMDRNN-dim2-layers2-units64-mixtures5-scale10.tflite"
size = "s" # Can be one of: xs, s, m, l, xl
sigmatemp = 0.01
pitemp = 1
timescale = 1

# MIDI Mapping
# MIDI Mapping
[midi]
in_device = "CASIO USB-MIDI 0"
out_device = "CASIO USB-MIDI 1"
input = [
  ["note_on", 1],  # Note On
]
output = [
  ["note_on", 1],  # Note On
]


[websocket]
server_ip = "0.0.0.0" # The address of this server
server_port = 5001 # The port this server should listen on.

[osc]
server_ip = "0.0.0.0" # Address of IMPSY
server_port = 6000 # Port IMPSY listens on
client_ip = "localhost" # Address of the output device
client_port = 6001 # Port of the output device