[tool.poetry]
name = "imps"
version = "0.4.0"
description = "IMPS is the Interactive Musical Prediction System, a tool for creative interactive intelligent musical instruments using a recurrent mixture density neural network."
authors = ["Charles Martin <cpm@charlesmartin.au>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
numpy = "^1.26.0"
pandas = "^2.0.3"
tensorflow = "^2.14"
tensorflow-io-gcs-filesystem = "0.34.0"
tensorflow-probability = "^0.19.0"
keras-mdn-layer = "^0.3.0"
python-osc = "^1.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
