[tool.poetry]
name = "imps"
version = "0.4.0"
description = "IMPS is the Interactive Musical Prediction System, a tool for creative interactive intelligent musical instruments using a recurrent mixture density neural network."
authors = ["Charles Martin <cpm@charlesmartin.au>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
tensorflow-probability = "0.23.0"
python-osc = "^1.8.3"
keras-mdn-layer = "^0.3.0"
pandas = "^2.0.3"
tensorflow-macos = {version = "2.15.0", platform = "darwin"}
tensorflow = {version = "2.15.0", platform = "linux"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
